name: personal_toolbox
description: Personal Toolbox App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  path_provider: ^1.6.24
  easy_localization: ^2.3.0
  adaptive_theme: ^1.1.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/en.json
    - assets/i18n/tr.json
